version: '3.1'

services:

  mongo:
    build: ./mongodb
    image: mongodb_reflectapp
    container_name: mongodb_reflectapp
    restart: unless-stopped
    volumes:
      - "./mongodb-data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: reflectapp-admin
      MONGO_INITDB_ROOT_PASSWORD: example123
      MONGO_INITDB_DATABASE: reflectapp

  reflectapp:
    build: ./app
    image: reflectapp
    container_name: reflectapp
    restart: unless-stopped
    volumes:
      - "./app/db:/usr/src/app/db"
      - "./app/media:/usr/src/app/client/dist/media"
    ports:
      - 4040:4040
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: reflectapp-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example123
      ME_CONFIG_MONGODB_DATABASE: reflectapp
